name: "Build & Deploy Backend + Frontend + Infra"

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BACK_IMAGE: "${{ vars.REGISTRY_LOGIN_SERVER }}/backend"
  FRONT_IMAGE: "${{ vars.REGISTRY_LOGIN_SERVER }}/frontend"

jobs:
  build_and_push:
    name: "Build and Push Docker Images"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure ACR
        run: |
          az acr login --name ${{ vars.REGISTRY_NAME }}
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Backend image
        uses: docker/build-push-action@v6
        with:
          context: ./ecommerce-app-backend
          push: true
          tags: |
            ${{ env.BACK_IMAGE }}:${{ github.sha }}
            ${{ env.BACK_IMAGE }}:latest

      - name: Build and push Frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./ecommerce-app-frontend
          push: true
          tags: |
            ${{ env.FRONT_IMAGE }}:${{ github.sha }}
            ${{ env.FRONT_IMAGE }}:latest

  terraform_deploy:
    name: "Terraform Init & Apply"
    runs-on: ubuntu-latest
    needs: build_and_push
    defaults:
      run:
        working-directory: infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="project_name=${{ vars.PROJECT_NAME }}" \
            -var="resource_group_name=${{ vars.RESOURCE_GROUP }}" \
            -var="location=westeurope" \
            -var="backend_image=${{ env.BACK_IMAGE }}:${{ github.sha }}" \
            -var="frontend_image=${{ env.FRONT_IMAGE }}:${{ github.sha }}" \
            -var="sql_admin_login=${{ secrets.SQL_ADMIN_LOGIN }}" \
            -var="sql_admin_password=${{ secrets.SQL_ADMIN_PASSWORD }}"
