name: "Terraform Deploy Only"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    env:
      # 🟡 Azure
      TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
      TF_VAR_location: ${{ vars.LOCATION }}
      TF_VAR_resource_group_name: ${{ vars.RESOURCE_GROUP }}

      # 🧠 Naming
      TF_VAR_author: ${{ vars.AUTHOR }}
      TF_VAR_resource_prefix: ${{ vars.RESOURCE_PREFIX }}

      # 🟠 Images
      TF_VAR_fe_image_name: ${{ vars.FE_IMAGE_NAME }}
      TF_VAR_fe_tag: ${{ vars.FE_TAG }}
      TF_VAR_be_image_name: ${{ vars.BE_IMAGE_NAME }}
      TF_VAR_be_tag: ${{ vars.BE_TAG }}
      #sql server
      TF_VAR_sql_admin_login: ${{ secrets.SQL_ADMIN_LOGIN }}
      TF_VAR_sql_admin_password: ${{ secrets.SQL_ADMIN_PASSWORD }}
      TF_VAR_sql_server_fqdn: ${{ secrets.SQL_SERVER_FQDN }}
      TF_VAR_sql_database_name: ${{ secrets.SQL_DATABASE_NAME }}
      TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
