name: "Terraform Deploy Only"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
           
      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Import Existing Resources
        working-directory: infra
        run: |
          terraform import azurerm_resource_group.resource_group \
          /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ vars.RESOURCE_GROUP }} || true
          
          terraform import azurerm_service_plan.service_plan["${{ vars.RESOURCE_PREFIX }}-fe-service-plan-${{ vars.AUTHOR }}"] \
          /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ vars.RESOURCE_GROUP }}/providers/Microsoft.Web/serverfarms/${{ vars.RESOURCE_PREFIX }}-fe-service-plan-${{ vars.AUTHOR }} || true

          terraform import azurerm_linux_web_app.fe_app \
          /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ vars.RESOURCE_GROUP }}/providers/Microsoft.Web/sites/${{ vars.RESOURCE_PREFIX }}-fe-app-${{ vars.AUTHOR }} || true

      
      - name: Terraform Apply
        working-directory: infra
        run: |
         terraform apply -auto-approve \
         -var="subscription_id=${{ secrets.SUBSCRIPTION_ID }}" \
         -var="location=${{ vars.LOCATION }}" \
         -var="resource_group_name=${{ vars.RESOURCE_GROUP }}" \
         -var="author=${{ vars.AUTHOR }}" \
         -var="resource_prefix=${{ vars.RESOURCE_PREFIX }}" \
         -var="fe_image_name=${{ vars.FE_IMAGE_NAME }}" \
         -var="fe_tag=${{ vars.FE_TAG }}"
 



