name: "Terraform Deploy Only"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    env:
      # 🟡 Azure
      TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
      TF_VAR_location: ${{ vars.LOCATION }}
      TF_VAR_resource_group_name: ${{ vars.RESOURCE_GROUP }}

      # 🧠 Naming
      TF_VAR_author: ${{ vars.AUTHOR }}
      TF_VAR_resource_prefix: ${{ vars.RESOURCE_PREFIX }}

      # 🟠 Images
      TF_VAR_fe_image_name: ${{ vars.FE_IMAGE_NAME }}
      TF_VAR_fe_tag: ${{ vars.FE_TAG }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Import Existing Resources (Optional)
        run: |
          terraform import azurerm_resource_group.resource_group \
          /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ vars.RESOURCE_GROUP }} || true

          terraform import azurerm_service_plan.service_plan["${{ vars.RESOURCE_PREFIX }}-fe-service-plan-${{ vars.AUTHOR }}"] \
          /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ vars.RESOURCE_GROUP }}/providers/Microsoft.Web/serverfarms/${{ vars.RESOURCE_PREFIX }}-fe-service-plan-${{ vars.AUTHOR }} || true

          terraform import azurerm_linux_web_app.fe_app \
          /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ vars.RESOURCE_GROUP }}/providers/Microsoft.Web/sites/${{ vars.RESOURCE_PREFIX }}-fe-app-${{ vars.AUTHOR }} || true

      - name: Terraform Apply
        run: terraform apply -auto-approve
